<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SkybrushExample</RootNamespace>
    <AssemblyName>SkybrushExample</AssemblyName>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SkybrushError.cs" />
    <Compile Include="YawControl.cs" />
    <Compile Include="YawPlayer.cs" />
    <Compile Include="Example.cs" />
  </ItemGroup>

</Project>
